version: '3'

services:
  db_service:
    container_name: db_container
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - intranet_of_any_name
    environment:
      - MYSQL_ROOT_PASSWORD=aabbcc
      - MYSQL_DATABASE=ddeeff
      - MYSQL_USER=gghhii
      - MYSQL_PASSWORD=jjkkll

  nextcloud_fpm_version:
    environment:
      - MYSQL_HOST=db_container:3306
      - MYSQL_DATABASE=ddeeff
      - MYSQL_USER=gghhii
      - MYSQL_PASSWORD=jjkkll
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud_vol:/var/www/html
    depends_on:
      - db_service
    networks:
      - intranet_of_any_name

  this_is_proxy_service:
    image: nginx:alpine
    restart: always
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/guoxiaokang.net/privkey.pem:/ssl/privkey.pem
      - /etc/letsencrypt/live/guoxiaokang.net/fullchain.pem:/ssl/fullchain.pem
      - nextcloud_vol:/var/www/html:ro
    depends_on:
      - nextcloud_fpm_version
    networks:
      - intranet_of_any_name

volumes:
  db_volume:
  nextcloud_vol:

networks:
  intranet_of_any_name:
